version: "3.8"

services:
  app_prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    volumes:
      - /home/node/app/dist
    depends_on:
      - db_prod
      - redis_prod
  db_prod:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis_prod:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
