FROM node:16.18.1-alpine

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package.json package-lock.json ./
RUN yarn

COPY --chown=node:node . .

RUN yarn build

CMD [ "yarn", "start:prod" ]